plugins {
    id("sapientia.shadow-conventions")
    id("sapientia.test-conventions")
    alias(libs.plugins.runpaper)
}

dependencies {
    api(project(":sapientia-api"))
    implementation(project(":sapientia-bedrock"))
    implementation(project(":sapientia-content"))

    compileOnly(libs.paper.api)
    compileOnly(libs.adventure.minimsg)

    // Embedded and relocated via shadow.
    implementation(libs.hikari)
    implementation(libs.snakeyaml)
    implementation(libs.kryo)

    // Paper ships the SQLite JDBC driver and registers it with DriverManager,
    // which is what Hikari resolves "jdbc:sqlite:" against. Keep the version in
    // step with the one bundled by the targeted Paper build.
    compileOnly(libs.sqlite.jdbc)
    testImplementation(libs.sqlite.jdbc)

    // Cloud command framework — catalog entries reserved for T-103 (0.2.0). Not
    // wired into any implementation() today to keep the shaded jar lean.

    // Floodgate soft-dep: only compileOnly so absent servers still load.
    compileOnly(libs.floodgate.api)

    testImplementation(libs.paper.api)
    testImplementation(libs.adventure.minimsg)
    testImplementation(libs.archunit.junit5)
    // MockBukkit is deferred to T-170 (sapientia-testkit) — no matching artifact
    // for Paper 26.x is published yet.
}

// Index of the bundled resource-pack assets (generated by scripts/textures). The
// plugin reads it at runtime to know which items have textures without having
// to scan its own jar.
val packSources = layout.projectDirectory.dir("src/main/resources/pack")
val packIndexDir = layout.buildDirectory.dir("generated/pack-index")
val generatePackIndex = tasks.register("generatePackIndex") {
    inputs.dir(packSources)
    outputs.dir(packIndexDir)
    doLast {
        val root = packSources.asFile
        val entries = root.walkTopDown()
            .filter { it.isFile }
            .map { it.relativeTo(root).invariantSeparatorsPath }
            .sorted()
            .toList()
        val out = packIndexDir.get().file("pack/index.txt").asFile
        out.parentFile.mkdirs()
        out.writeText(entries.joinToString("\n", postfix = "\n"))
    }
}
sourceSets.main {
    resources.srcDir(generatePackIndex)
}

tasks.processResources {
    val props = mapOf("version" to project.version)
    inputs.properties(props)
    filesMatching("plugin.yml") {
        expand(props)
    }
}

tasks.named<xyz.jpenilla.runpaper.task.RunServer>("runServer") {
    minecraftVersion("26.3")
}
