package dev.brmz.sapientia.api.mining;

import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.random.RandomGenerator;

import dev.brmz.sapientia.api.progression.Era;
import org.bukkit.NamespacedKey;
import org.bukkit.World;
import org.bukkit.block.Block;
import org.bukkit.inventory.ItemStack;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * Minerals, natural terrain and separation.
 *
 * <p><b>Natural terrain.</b> Only blocks generated by the world yield
 * minerals. Blocks placed by players, formed by lava and water, or moved by
 * pistons are remembered per chunk section and never drop fragments;
 * explosions never drop them either.
 *
 * <p><b>Drops.</b> Breaking a natural host block may drop one fragment of a
 * mineral picked by host block, height, biome, dimension and the veins of the
 * world seed. Minerals of locked eras do not drop. Fortune raises the chance,
 * Silk Touch prevents it, and each mineral needs a minimum pickaxe for its era.
 */
public interface MiningService {

    /** Registers a mineral. Its fragment and tailings items should be registered too. */
    void registerMineral(@NotNull Mineral mineral);

    /** Declares the era from which an element can be separated out of minerals. */
    void registerElement(@NotNull String element, @NotNull Era era);

    /** Registers a separation method. */
    void registerSeparationMethod(@NotNull SeparationMethod method);

    @NotNull Collection<Mineral> minerals();

    @NotNull Optional<Mineral> mineral(@NotNull NamespacedKey id);

    /** The mineral whose fragment or tailings item has this id. */
    @NotNull Optional<Mineral> mineralOfItem(@NotNull NamespacedKey itemId);

    @NotNull Collection<SeparationMethod> separationMethods();

    @NotNull Optional<SeparationMethod> separationMethod(@NotNull NamespacedKey id);

    /** Era of an element, or {@code null} if it was never registered. */
    @Nullable Era elementEra(@NotNull String element);

    /** Whether the block was generated by the world and never placed, formed or moved. */
    boolean isNatural(@NotNull Block block);

    /** Marks the block as not natural (for example after a machine or addon placed it). */
    void markPlaced(@NotNull Block block);

    /**
     * Fragments that breaking {@code block} with {@code tool} yields, for
     * machines and addons that break blocks on a player's behalf. Returns an
     * empty list for placed blocks and locked minerals.
     */
    @NotNull List<ItemStack> rollFragments(@NotNull Block block, @Nullable ItemStack tool);

    /**
     * Separates one fragment (or, with {@code fromTailings}, one tailings item,
     * which yields only byproducts and never leaves tailings again). Elements of
     * locked eras stay in the tailings.
     */
    @NotNull SeparationResult separate(@NotNull Mineral mineral, @NotNull SeparationMethod method,
                                       boolean fromTailings, @NotNull RandomGenerator random);

    /** The mineral concentrated in the vein covering a chunk, if any. */
    @NotNull Optional<Mineral> veinAt(@NotNull World world, int chunkX, int chunkZ);
}
