package dev.brmz.sapientia.core.mining;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import dev.brmz.sapientia.core.collect.LongObjectMap;
import dev.brmz.sapientia.core.engine.BlockPositions;
import org.bukkit.Chunk;
import org.bukkit.NamespacedKey;
import org.bukkit.World;
import org.bukkit.block.Block;
import org.bukkit.persistence.PersistentDataContainer;
import org.bukkit.persistence.PersistentDataType;
import org.jetbrains.annotations.NotNull;

/**
 * Remembers which blocks were placed, formed or moved, so only terrain
 * generated by the world yields minerals.
 *
 * <p>Each chunk keeps a 4096-bit map (64 longs) per 16-block section, only for
 * sections where something was placed, in the chunk's own persistent data: it
 * saves and loads with the chunk and costs nothing for untouched terrain.
 * Maps are read lazily on first use and kept in memory while the chunk is
 * loaded; every change is written straight back to the chunk.
 *
 * <p>Chunks generated before the plugin was installed carry no marks. They
 * count as natural unless {@code legacyNatural} is off, in which case only
 * chunks generated afterwards (flagged on generation) yield minerals.
 */
public final class PlacedBlockTracker {

    private static final String SECTION_PREFIX = "placed_";

    private final NamespacedKey trackedKey;
    private final String namespace;
    private final boolean legacyNatural;
    private final Map<UUID, LongObjectMap<ChunkMarks>> worlds = new HashMap<>();

    public PlacedBlockTracker(@NotNull String namespace, boolean legacyNatural) {
        this.namespace = namespace;
        this.trackedKey = new NamespacedKey(namespace, "terrain_tracked");
        this.legacyNatural = legacyNatural;
    }

    /** Whether the block was generated by the world and never placed, formed or moved. */
    public boolean isNatural(@NotNull Block block) {
        ChunkMarks marks = marks(block.getChunk());
        if (!legacyNatural && !marks.tracked) return false;
        long[] bits = marks.sections.get(block.getY() >> 4);
        return bits == null || !SectionBits.get(bits, SectionBits.index(block.getX(), block.getY(), block.getZ()));
    }

    public void markPlaced(@NotNull Block block) {
        set(block, true);
    }

    /** Clears the mark, for natural sand or gravel that fell onto a spot where something was placed before. */
    public void markNatural(@NotNull Block block) {
        set(block, false);
    }

    /** Marks every block of a box as placed (for builds pasted with editing tools). Returns the blocks marked. */
    public long markRegion(@NotNull World world, int x1, int y1, int z1, int x2, int y2, int z2) {
        int minX = Math.min(x1, x2), maxX = Math.max(x1, x2);
        int minY = Math.max(world.getMinHeight(), Math.min(y1, y2));
        int maxY = Math.min(world.getMaxHeight() - 1, Math.max(y1, y2));
        int minZ = Math.min(z1, z2), maxZ = Math.max(z1, z2);
        long count = 0;
        for (int cx = minX >> 4; cx <= maxX >> 4; cx++) {
            for (int cz = minZ >> 4; cz <= maxZ >> 4; cz++) {
                Chunk chunk = world.getChunkAt(cx, cz);
                ChunkMarks marks = marks(chunk);
                for (int sy = minY >> 4; sy <= maxY >> 4; sy++) {
                    long[] bits = marks.sections.computeIfAbsent(sy, k -> new long[SectionBits.LONGS]);
                    for (int x = Math.max(minX, cx << 4); x <= Math.min(maxX, (cx << 4) + 15); x++) {
                        for (int z = Math.max(minZ, cz << 4); z <= Math.min(maxZ, (cz << 4) + 15); z++) {
                            for (int y = Math.max(minY, sy << 4); y <= Math.min(maxY, (sy << 4) + 15); y++) {
                                SectionBits.set(bits, SectionBits.index(x, y, z), true);
                                count++;
                            }
                        }
                    }
                    chunk.getPersistentDataContainer().set(sectionKey(sy), PersistentDataType.LONG_ARRAY, bits);
                }
            }
        }
        return count;
    }

    /** Flags a freshly generated chunk as tracked from its first tick. */
    public void onChunkGenerated(@NotNull Chunk chunk) {
        chunk.getPersistentDataContainer().set(trackedKey, PersistentDataType.BYTE, (byte) 1);
        ChunkMarks marks = cached(chunk);
        if (marks != null) marks.tracked = true;
    }

    /** Forgets the in-memory copy of an unloading chunk (the data stays in the chunk). */
    public void onChunkUnloaded(@NotNull Chunk chunk) {
        LongObjectMap<ChunkMarks> chunks = worlds.get(chunk.getWorld().getUID());
        if (chunks != null) chunks.remove(BlockPositions.chunk(chunk.getX(), chunk.getZ()));
    }

    public void onWorldUnloaded(@NotNull World world) {
        worlds.remove(world.getUID());
    }

    private void set(Block block, boolean placed) {
        Chunk chunk = block.getChunk();
        ChunkMarks marks = marks(chunk);
        int sectionY = block.getY() >> 4;
        long[] bits = marks.sections.get(sectionY);
        if (bits == null) {
            if (!placed) return;
            bits = new long[SectionBits.LONGS];
            marks.sections.put(sectionY, bits);
        }
        int index = SectionBits.index(block.getX(), block.getY(), block.getZ());
        if (SectionBits.get(bits, index) == placed) return;
        SectionBits.set(bits, index, placed);
        chunk.getPersistentDataContainer().set(sectionKey(sectionY), PersistentDataType.LONG_ARRAY, bits);
    }

    private ChunkMarks cached(Chunk chunk) {
        LongObjectMap<ChunkMarks> chunks = worlds.get(chunk.getWorld().getUID());
        return chunks == null ? null : chunks.get(BlockPositions.chunk(chunk.getX(), chunk.getZ()));
    }

    private ChunkMarks marks(Chunk chunk) {
        LongObjectMap<ChunkMarks> chunks = worlds.computeIfAbsent(chunk.getWorld().getUID(), k -> new LongObjectMap<>());
        long key = BlockPositions.chunk(chunk.getX(), chunk.getZ());
        ChunkMarks marks = chunks.get(key);
        if (marks == null) {
            marks = load(chunk.getPersistentDataContainer());
            chunks.put(key, marks);
        }
        return marks;
    }

    private ChunkMarks load(PersistentDataContainer pdc) {
        ChunkMarks marks = new ChunkMarks();
        marks.tracked = pdc.has(trackedKey, PersistentDataType.BYTE);
        for (NamespacedKey key : pdc.getKeys()) {
            if (!key.getNamespace().equals(namespace) || !key.getKey().startsWith(SECTION_PREFIX)) continue;
            try {
                int sectionY = Integer.parseInt(key.getKey().substring(SECTION_PREFIX.length()));
                long[] bits = pdc.get(key, PersistentDataType.LONG_ARRAY);
                if (bits != null && bits.length == SectionBits.LONGS) marks.sections.put(sectionY, bits);
            } catch (NumberFormatException ignored) {
                // not one of ours
            }
        }
        return marks;
    }

    private NamespacedKey sectionKey(int sectionY) {
        return new NamespacedKey(namespace, SECTION_PREFIX + sectionY);
    }

    private static final class ChunkMarks {
        boolean tracked;
        final Map<Integer, long[]> sections = new HashMap<>(4);
    }
}
